# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$git_branch $git_metrics $fill $time
$character
"""

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[character]
success_symbol = "[](bold)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold)"
vimcmd_replace_one_symbol = "[](bold yellow)"
vimcmd_replace_symbol = "[](bold yellow)"
vimcmd_visual_symbol = "[](bold orange)"

[directory]
style = "cyan"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = ".../"

[time]
disabled = false
style = "bright-black"
format = "[$time]($style)"
use_12hr = true

[git_branch]
style = "purple"
symbol = " "
format = "[:](bright-black) [$branch(:$remote_branch)$symbol]($style)"

[git_metrics]
disabled = false
format = "([+$added]($added_style) )([-$deleted]($deleted_style))"

[fill]
symbol = " "
