# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$git_branch $python$nodejs
$character
"""

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[character]
success_symbol = "[󰅂](bold)"
error_symbol = "[󰅂](bold red)"
vimcmd_symbol = "[󰅁](bold)"
vimcmd_replace_one_symbol = "[󰅁](bold)"
vimcmd_replace_symbol = "[󰅁](bold)"
vimcmd_visual_symbol = "[󰅁](bold)"

[directory]
style = "green bold"
truncate_to_repo = true
truncation_length = 3

[time]
disabled = false
style = "bright-black"
format = "[$time]($style)"
use_12hr = true

[git_branch]
style = "purple"
symbol = " "
format = "[|](#26233a) [$symbol$branch(:$remote_branch)]($style)"
truncation_length = 25

[python]
style = "yellow"
symbol = " "
format = "[|](#26233a) [$symbol$virtualenv]($style)"

[nodejs]
style = "green"
symbol = "󰎙 "
format = "[|](#26233a) [$symbol$version]($style)"

[fill]
symbol = " "
