#!/usr/bin/env bash
# fzfp = fuzzy find project

dirs=(~/projects ~/work ~/personal ~/university)

selected=$(find "${dirs[@]}" -maxdepth 1 -type d | fzf --height ~60%)
if [[ -z $selected ]]; then
    exit 0
fi

echo $selected
