#!/usr/bin/env bash
# fzfp = fuzzy find project

dirs=(~/projects ~/work ~/personal ~/university)

selected=$(fd --max-depth=1 --type=d . "${dirs[@]}" | fzf --height ~60%)
if [[ -z $selected ]]; then
    exit 0
fi

echo $selected
