#!/usr/bin/env zsh

# selp = select project
# let's you select a project dir from the list with fzf

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/projects ~/work ~/personal -mindepth 1 -maxdepth 1 -type d | fzf )
fi

if [[ -z $selected ]]; then
    exit 0
fi

echo $selected
