#!/usr/bin/env bash

selected=`~/.config/.scripts/fzfp $1`

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=`basename "$selected" | tr . _`
tmux_running=`pgrep tmux`

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-window -c $selected \; rename-window $selected_name
    exit 0
fi

has_window=`tmux lsw -F "#{window_name}" | grep $selected_name`
if [[ -z $has_window ]]; then
    tmux new-window -c $selected \; rename-window $selected_name
fi

tmux select-window -t $selected_name

