#!/usr/bin/env bash

selected=`~/.config/.scripts/fzfp $1`

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=`basename "$selected" | tr . _`
tmux_running=`pgrep tmux`

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

has_session=`tmux has-session -t=$selected_name 2> /dev/null`
if [[ -z $has_session ]]; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

