#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/projects ~/work ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-window -c $selected \; rename-window $selected_name
    exit 0
fi

has_window=`tmux lsw -F "#{window_name}" | grep $selected_name`
if [[ -z $has_window ]]; then
    tmux new-window -c $selected \; rename-window $selected_name
fi

# switch to existing window and not session, by name
tmux select-window -t $selected_name

