#!/usr/bin/env zsh

selected=`$HOME/.config/.scripts/fzfp $1`
selected_name=$(basename "$selected" | tr . _)

if [[ -z $selected ]]; then
    exit 0
fi

paneid=`wezterm cli spawn --cwd $selected`

wezterm cli set-tab-title --pane-id $paneid $selected_name
