[colors]
background = "#000000"
foreground = "#e0e2ea"
cursor_bg = "#e0e2ea"
cursor_fg = "#07080d"
cursor_border = "#a6dbff"
selection_bg = "#4f5258"

ansi = [
  "#4f5258",
  "#ffc0b9",
  "#b4f6c0",
  "#fce094",
  "#a6dbff",
  "#ffcaff",
  "#8cf8f7",
  "#eef1f8",
]

brights = [
  "#4f5258",
  "#ffc0b9",
  "#b4f6c0",
  "#fce094",
  "#a6dbff",
  "#ffcaff",
  "#8cf8f7",
  "#eef1f8",
]

[colors.tab_bar]
background = "none"

[colors.tab_bar.active_tab]
bg_color = "#07080d"
fg_color = "#e0e2ea"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "none"
fg_color = "#4f5258"

[colors.tab_bar.inactive_tab_hover]
bg_color = "none"
fg_color = "#4f5258"
